[workspace]
authors = ["Daniel S. Roche <roche@usna.edu>"]
channels = ["conda-forge"]
name = "sd212"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
wikipedia = ">=1.4.0,<2"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
ipython = ">=9.9.0,<10"
numpy = ">=2.4.0,<3"
ipykernel = ">=7.1.0,<8"
plotly = ">=6.5.0,<7"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"
opencv = ">=4.12.0,<5"
bs4 = ">=4.14.3,<5"
lxml = ">=6.0.2,<7"
nltk = ">=3.9.2,<4"
easygui = ">=0.98.3,<0.99"
mypy = ">=1.19.1,<2"
openpyxl = ">=3.1.5,<4"
pandas-stubs = ">=2.3.3.251219,<3"
flask = ">=3.1.2,<4"
pypdf = ">=6.5.0,<7"
pycryptodome = ">=3.23.0,<4"
requests = ">=2.32.5,<3"
nbformat = ">=5.10.4,<6"
